declare namespace App.Data {
export type AddressCategoryData = {
id: number | null;
name: string;
is_invoice_address: boolean | null;
};
export type AttachmentData = {
id: number | null;
attachable_id: number;
attachable_type: string;
document_id: number;
pos: number;
days: number | null;
amount: number | null;
is_currency_difference: boolean | null;
document: App.Data.DocumentData;
};
export type BankAccountData = {
id: number | null;
name: string;
iban: string;
bic: string;
bank_code: string;
prefix: string;
bookkeeping_account_id: string;
pos: number;
};
export type BillableProjectData = {
id: number | null;
name: string;
total_mins: number;
first_entry_at: string | null;
last_entry_at: string | null;
};
export type BookingPolicyData = {
id: number | null;
name: string;
is_default: boolean;
age_min: number | null;
arrival_days: Array<any> | null;
departure_days: Array<any> | null;
stay_min: number | null;
stay_max: number | null;
checkin: string | null;
checkout: string | null;
};
export type BookkeepingAccountData = {
id: number | null;
account_number: number;
name: string;
label: string;
type: string;
tax: App.Data.TaxData | null;
};
export type BookkeepingBookingData = {
id: number | null;
account_id_credit: number;
account_id_debit: number;
amount: number;
date: string | null;
tax_id: number;
is_split: boolean;
split_id: number;
booking_text: string;
note: string | null;
tax_credit: number;
tax_debit: number;
is_locked: boolean;
is_marked: boolean;
bookable_type: string;
bookable_id: number;
number_range_document_numbers_id: number;
document_number: string | null;
created_at: string | null;
updated_at: string | null;
is_canceled: boolean;
canceled_id: number | null;
balance: number | null;
balance_type: string | null;
counter_account: number | null;
counter_account_label: string | null;
amount_net: number | null;
account_credit: App.Data.BookkeepingAccountData | null;
account_debit: App.Data.BookkeepingAccountData | null;
tax: App.Data.TaxData | null;
};
export type BookkeepingRuleActionData = {
id: number | null;
bookkeeping_rule_id: number;
field: string;
value: string;
};
export type BookkeepingRuleConditionData = {
id: number | null;
bookkeeping_rule_id: number;
field: string;
logical_condition: string;
value: string;
};
export type BookkeepingRuleData = {
id: number | null;
name: string;
priority: number;
is_active: boolean;
table: string;
logical_operator: string;
action_type: string;
type: string;
conditions: Array<App.Data.BookkeepingRuleConditionData> | null;
actions: Array<App.Data.BookkeepingRuleActionData> | null;
};
export type CompanyData = {
id: number | null;
name: string;
first_name: string | null;
full_name: string;
reverse_full_name: string;
initials: string;
title_id: number | null;
salutation_id: number | null;
creditor_number: string | null;
is_favorite: boolean | null;
is_org: boolean | null;
debtor_number: string | null;
primary_mail: string | null;
vat_id: string | null;
short_name: string | null;
register_court: string | null;
register_number: string | null;
department: string | null;
position: string | null;
tax_number: string | null;
formated_debtor_number: string | null;
formated_creditor_number: string | null;
payment_deadline_id: string | null;
tax_id: string | null;
iban: string | null;
paypal_email: string | null;
cc_name: string | null;
outturn_account_id: number | null;
website: string | null;
is_primary: boolean | null;
is_debtor: boolean | null;
is_creditor: boolean | null;
primary_phone: string | null;
cost_center_id: number | null;
cost_center: App.Data.CostCenterData | null;
avatar_url: string | null;
outturn_account: App.Data.BookkeepingAccountData | null;
contacts: Array<App.Data.ContactData> | null;
title: App.Data.TitleData | null;
salutation: App.Data.SalutationData | null;
payment_deadline: App.Data.PaymentDeadlineData | null;
tax: App.Data.TaxData | null;
mails: Array<App.Data.ContactMailData> | null;
phones: Array<App.Data.ContactPhoneData> | null;
sales: App.Data.SalesData | null;
addresses: Array<App.Data.ContactAddressData> | null;
};
export type ContactAddressData = {
id: number | null;
contact_id: number;
address: string;
zip: string;
city: string;
country_id: number;
full_address: string;
address_category_id: number;
category: App.Data.AddressCategoryData | null;
country: App.Data.CountryData | null;
};
export type ContactData = {
id: number | null;
name: string;
first_name: string | null;
company_name: string | null;
company_id: number | null;
full_name: string;
reverse_full_name: string;
initials: string;
title_id: number | null;
salutation_id: number | null;
creditor_number: string | null;
note: string | null;
is_favorite: boolean | null;
is_org: boolean | null;
debtor_number: string | null;
primary_mail: string | null;
vat_id: string | null;
short_name: string | null;
register_court: string | null;
register_number: string | null;
department: string | null;
position: string | null;
tax_number: string | null;
formated_debtor_number: string | null;
formated_creditor_number: string | null;
payment_deadline_id: number | null;
tax_id: number | null;
iban: string | null;
paypal_email: string | null;
cc_name: string | null;
outturn_account_id: number | null;
website: string | null;
is_primary: boolean | null;
is_debtor: boolean | null;
is_archived: boolean | null;
is_creditor: boolean | null;
has_dunning_block: boolean | null;
primary_phone: string | null;
cost_center_id: number | null;
cost_center: App.Data.CostCenterData | null;
avatar_url: string | null;
outturn_account: App.Data.BookkeepingAccountData | null;
company: App.Data.CompanyData | null;
dob: string | null;
contacts: Array<App.Data.ContactData> | null;
title: App.Data.TitleData | null;
salutation: App.Data.SalutationData | null;
payment_deadline: App.Data.PaymentDeadlineData | null;
tax: App.Data.TaxData | null;
mails: Array<App.Data.ContactMailData> | null;
phones: Array<App.Data.ContactPhoneData> | null;
sales: App.Data.SalesData | null;
addresses: Array<App.Data.ContactAddressData> | null;
notables: Array<App.Data.NoteableData> | null;
};
export type ContactMailData = {
id: number | null;
contact_id: number;
email: string;
pos: number;
email_category_id: number;
category: App.Data.EmailCategoryData | null;
};
export type ContactPhoneData = {
id: number | null;
contact_id: number;
phone: string;
pos: number;
phone_category_id: number;
category: App.Data.PhoneCategoryData | null;
};
export type CostCenterData = {
id: number | null;
name: string;
bookkeeping_account_id: number | null;
account: App.Data.BookkeepingAccountData | null;
};
export type CountryData = {
id: number;
name: string;
iso_code: string;
vehicle_code: string;
country_code: string;
};
export type CurrencyData = {
id: number | null;
name: string;
code: string;
};
export type DocumentData = {
id: number | null;
document_type_id: number | null;
sender_contact_id: number | null;
receiver_contact_id: number | null;
project_id: number | null;
filename: string;
mime_type: string;
file_size: number;
pages: number;
issued_on: string | null;
sent_on: string | null;
received_on: string | null;
deleted_at: string | null;
is_inbound: boolean | null;
is_hidden: boolean | null;
source_file: string | null;
folder: string;
title: string;
label: string | null;
summary: string | null;
reference: string | null;
is_pinned: boolean;
is_confirmed: boolean;
sender_contact: App.Data.ContactData | null;
receiver_contact: App.Data.ContactData | null;
type: App.Data.DocumentTypeData | null;
project: App.Data.ProjectData | null;
};
export type DocumentTypeData = {
id: number | null;
parent_id: number | null;
name: string;
color: string | null;
icon: string | null;
};
export type EmailCategoryData = {
id: number | null;
name: string;
type: number | null;
};
export type InboxData = {
id: number | null;
name: string;
is_default: boolean;
email_address: string;
};
export type InvoiceData = {
id: number | null;
contact_id: number;
project_id: number;
invoice_contact_id: number;
type_id: number;
invoice_number: number | null;
payment_deadline_id: number;
document_id: number | null;
is_external: boolean;
issued_on: string;
due_on: string | null;
service_period_begin: string | null;
service_period_end: string | null;
dunning_block: boolean;
is_draft: boolean;
is_loss_of_receivables: boolean;
service_provision: string | null;
vat_id: string | null;
address: string | null;
filename: string | null;
document_number: string | null;
booking: App.Data.BookkeepingBookingData | null;
invoice_address: Array<any>;
formated_invoice_number: string;
amount_net: number;
amount_tax: number;
amount_gross: number;
payable_sum_amount: number | null;
amount_open: number | null;
is_recurring: boolean;
recurring_interval_units: number | null;
additional_text: string | null;
recurring_interval: App.Enums.InvoiceRecurringEnum | null;
payable: App.Data.PaymentData | null;
parent_id: number | null;
tax_id: number | null;
parent_invoice: App.Data.InvoiceData | null;
sent_at: string | null;
recurring_begin_on: string | null;
recurring_end_on: string | null;
type: App.Data.InvoiceTypeData | null;
contact: App.Data.ContactData | null;
invoice_contact: App.Data.ContactData | null;
project: App.Data.ProjectData | null;
payment_deadline: App.Data.PaymentDeadlineData | null;
lines: Array<App.Data.InvoiceLineData> | null;
tax: App.Data.TaxData | null;
offer_id: number | null;
offer: App.Data.OfferData | null;
};
export type InvoiceLineData = {
id: number | null;
invoice_id: number;
type_id: number;
pos: number;
tax_id: number;
quantity: number | null;
unit: string | null;
text: string;
price: number | null;
amount: number | null;
tax: number | null;
tax_rate_id: number;
rate: App.Data.TaxRateData | null;
service_period_begin: string | null;
service_period_end: string | null;
linked_invoice: App.Data.InvoiceData | null;
};
export type InvoiceTypeData = {
id: number | null;
print_name: string;
display_name: string;
abbreviation: string;
key: string;
};
export type LetterheadData = {
id: number | null;
title: string;
css: string | null;
is_multi: boolean;
is_default: boolean;
};
export type LoginData = {
email: string;
password: string;
remember: boolean | null;
};
export type NoteableData = {
id: number;
notable_id: number;
note: string;
creator: App.Data.UserData;
created_at: string;
updated_at: string;
};
export type OfferData = {
id: number | null;
contact_id: number;
project_id: number;
offer_number: number | null;
issued_on: string;
valid_until: string | null;
is_draft: boolean;
filename: string | null;
formated_offer_number: string;
amount_net: number;
amount_tax: number;
amount_gross: number;
additional_text: string | null;
parent_id: number | null;
tax_id: number | null;
address: string | null;
sent_at: string | null;
recurring_end_on: string | null;
contact: App.Data.ContactData | null;
project: App.Data.ProjectData | null;
sections: Array<App.Data.OfferOfferSectionData> | null;
lines: Array<App.Data.OfferLineData> | null;
attachments: Array<App.Data.AttachmentData> | null;
tax: App.Data.TaxData | null;
is_template: boolean | null;
template_name: string | null;
};
export type OfferLineData = {
id: number | null;
offer_id: number;
type_id: number;
pos: number;
tax_id: number;
quantity: number | null;
unit: string | null;
text: string;
price: number | null;
amount: number | null;
tax: number | null;
tax_rate_id: number;
rate: App.Data.TaxRateData | null;
};
export type OfferOfferSectionData = {
id: number | null;
offer_id: number;
section_id: number;
pos: number;
title: string | null;
content: string | null;
pagebreak: App.Enums.PagebreakEnum | null;
};
export type OfferSectionData = {
id: number | null;
name: string;
default_content: string | null;
pagebreak: App.Enums.PagebreakEnum | null;
};
export type PaymentData = {
id: number | null;
payable_type: string;
payable_id: number;
days: number | null;
amount: number | null;
is_currency_difference: boolean | null;
transaction_id: number;
transaction: App.Data.TransactionData;
issued_on: string;
};
export type PaymentDeadlineData = {
id: number | null;
name: string;
days: number | null;
is_immediately: boolean | null;
is_default: boolean | null;
};
export type PhoneCategoryData = {
id: number | null;
name: string;
type: number | null;
};
export type PrintLayoutData = {
id: number | null;
name: string;
title: string;
css: string | null;
letterhead_id: number;
letterhead: App.Data.LetterheadData;
};
export type ProjectCategoryData = {
id: number | null;
name: string;
color: string | null;
icon: string | null;
};
export type ProjectData = {
id: number | null;
name: string;
website: string | null;
owner_contact_id: number | null;
lead_user_id: number | null;
manager_contact_id: number | null;
project_category_id: number;
is_archived: boolean;
hourly: number;
budget_hours: number | null;
budget_costs: number | null;
budget_period: string | null;
avatar_url: string | null;
begin_on: string | null;
end_on: string | null;
owner: App.Data.ContactData | null;
user: App.Data.UserData | null;
manager: App.Data.ContactData | null;
category: App.Data.ProjectCategoryData | null;
};
export type ReceiptData = {
id: number | null;
reference: string;
issued_on: string;
org_filename: string;
file_size: number;
file_created_at: string;
open_amount: number;
payable_min_issued_on: string | null;
contact_id: number | null;
cost_center_id: number | null;
bookkeeping_account_id: number | null;
org_currency: string | null;
org_amount: number | null;
amount: number;
exchange_rate: number | null;
document_number: string | null;
duplicate_of: number | null;
is_foreign_currency: boolean | null;
is_confirmed: boolean | null;
is_locked: boolean;
bookings_count: number | null;
iban: string | null;
number_range_document_number_id: number | null;
account: App.Data.BookkeepingAccountData | null;
contact: App.Data.ContactData | null;
cost_center: App.Data.CostCenterData | null;
number_range_document_number: any | null;
checksum: string;
text: string | null;
data: Array<any> | null;
payable_sum: number | null;
payable: Array<App.Data.PaymentData> | null;
bookings: Array<App.Data.BookkeepingBookingData> | null;
created_at: string;
updated_at: string;
};
export type RegionData = {
id: number;
country_id: number;
name: string;
short_name: string;
place_short_name: string;
};
export type SalesData = {
currentYear: number;
allTime: number;
};
export type SalutationData = {
id: number | null;
name: string;
is_hidden: boolean;
gender: string;
};
export type SettingData = {
group: string;
key: string;
value: string | null;
};
export type TaxData = {
id: number | null;
name: string;
invoice_text: string;
needs_vat_id: boolean;
is_default: boolean;
value: number;
default_rate_id: number;
rates: Array<App.Data.TaxRateData> | null;
};
export type TaxRateData = {
id: number | null;
tax_id: number;
rate: number;
name: string;
};
export type TenantData = {
first_name: string;
last_name: string;
organisation: string;
email: string;
website: string;
subdomain: string;
prefix: string;
formated_prefix: string;
};
export type TextModuleData = {
id: number | null;
title: string | null;
content: string | null;
};
export type TimeCategoryData = {
id: number | null;
name: string;
short_name: string;
pos: number;
is_default: boolean;
hourly: number;
};
export type TimeData = {
id: number | null;
project_id: number;
time_category_id: number;
subproject_id: number | null;
task_id: number | null;
invoice_id: number | null;
user_id: number;
note: string | null;
begin_at: string;
end_at: string | null;
date: string;
is_locked: boolean;
is_billable: boolean;
is_timer: boolean;
minutes: number | null;
mins: number | null;
ping_at: string | null;
created_at: string | null;
updated_at: string | null;
deleted_at: string | null;
project: App.Data.ProjectData | null;
subproject: App.Data.ProjectData | null;
category: App.Data.TimeCategoryData | null;
user: App.Data.UserData | null;
};
export type TitleData = {
id: number | null;
name: string;
correspondence_salutation_male: string;
correspondence_salutation_female: string;
correspondence_salutation_other: string;
};
export type TransactionData = {
id: number | null;
mm_ref: string;
contact_id: number;
bank_account_id: number;
valued_on: string;
booked_on: string | null;
comment: string | null;
currency: string;
booking_key: string | null;
bank_code: string | null;
account_number: string | null;
name: string;
purpose: string | null;
amount: number;
remaining_amount: number;
is_private: boolean;
created_at: string | null;
updated_at: string | null;
prefix: string;
booking_text: string | null;
type: string | null;
return_reason: string | null;
transaction_code: string | null;
end_to_end_reference: string | null;
mandate_reference: string | null;
batch_reference: string | null;
primanota_number: string | null;
is_transit: boolean;
booking_id: number | null;
org_category: string | null;
amount_in_foreign_currency: number;
number_range_document_numbers_id: number | null;
document_number: string | null;
foreign_currency: string | null;
counter_account_id: number;
is_locked: boolean;
bookkeeping_text: string;
contact: App.Data.ContactData | null;
account: App.Data.BookkeepingAccountData | null;
booking: App.Data.BookkeepingBookingData | null;
};
export type UserData = {
id: number | null;
first_name: string;
last_name: string;
avatar_url: string | null;
is_admin: boolean;
is_locked: boolean;
email: string;
full_name: string;
reverse_full_name: string;
initials: string;
user_agent: string | null;
pending_email: string | null;
is_impersonating: boolean | null;
impersonator: string | null;
last_login_at: string | null;
email_verified_at: string | null;
};
}
declare namespace App.Enums {
export type InvoiceRecurringEnum = 'days' | 'weeks' | 'months' | 'years';
export type PagebreakEnum = 'after' | 'before' | 'both' | 'none';
}
