declare namespace App {
  namespace Data {
    export type AddressCategoryData = {
      readonly id: number | null;
      readonly name: string;
      readonly is_invoice_address: boolean | null;
    };
    export type AttachmentData = {
      readonly id: number | null;
      readonly attachable_id: number;
      readonly attachable_type: string;
      readonly document_id: number;
      readonly pos: number;
      readonly days: number | null;
      readonly amount: number | null;
      readonly is_currency_difference: boolean | null;
      readonly document: App.Data.DocumentData;
    };
    export type BankAccountData = {
      readonly id: number | null;
      readonly name: string | null;
      readonly iban: string | null;
      readonly bic: string | null;
      readonly prefix: string | null;
      readonly email: string | null;
      readonly bank_name: string | null;
      readonly account_owner: string | null;
      readonly bookkeeping_account_id: number | null;
      readonly pos: number | null;
      readonly is_default: boolean | null;
      readonly is_paypal: boolean | null;
      readonly is_closed: boolean | null;
    };
    export type BillableProjectData = {
      readonly id: number | null;
      readonly name: string;
      readonly total_mins: number;
      readonly first_entry_at: string | null;
      readonly last_entry_at: string | null;
    };
    export type BookingPolicyData = {
      readonly id: number | null;
      readonly name: string;
      readonly is_default: boolean;
      readonly age_min: number | null;
      readonly arrival_days: Array<any> | null;
      readonly departure_days: Array<any> | null;
      readonly stay_min: number | null;
      readonly stay_max: number | null;
      readonly checkin: string | null;
      readonly checkout: string | null;
    };
    export type BookkeepingAccountData = {
      readonly id: number | null;
      readonly account_number: number;
      readonly name: string;
      readonly label: string;
      readonly type: string;
      readonly tax: App.Data.TaxData | null;
    };
    export type BookkeepingBookingData = {
      readonly id: number | null;
      readonly account_id_credit: number;
      readonly account_id_debit: number;
      readonly amount: number;
      readonly date: string | null;
      readonly tax_id: number;
      readonly is_split: boolean;
      readonly split_id: number;
      readonly booking_text: string;
      readonly note: string | null;
      readonly tax_credit: number;
      readonly tax_debit: number;
      readonly is_locked: boolean;
      readonly is_marked: boolean;
      readonly bookable_type: string;
      readonly bookable_id: number;
      readonly number_range_document_numbers_id: number;
      readonly document_number: string | null;
      readonly created_at: string | null;
      readonly updated_at: string | null;
      readonly is_canceled: boolean;
      readonly canceled_id: number | null;
      readonly balance: number | null;
      readonly balance_type: string | null;
      readonly counter_account: number | null;
      readonly counter_account_label: string | null;
      readonly amount_net: number | null;
      readonly account_credit: App.Data.BookkeepingAccountData;
      readonly account_debit: App.Data.BookkeepingAccountData;
      readonly tax: App.Data.TaxData;
    };
    export type BookkeepingRuleActionData = {
      readonly id: number | null;
      readonly bookkeeping_rule_id: number;
      readonly field: string;
      readonly value: string;
    };
    export type BookkeepingRuleConditionData = {
      readonly id: number | null;
      readonly bookkeeping_rule_id: number;
      readonly field: string;
      readonly logical_condition: string;
      readonly value: string;
    };
    export type BookkeepingRuleData = {
      readonly id: number | null;
      readonly name: string;
      readonly priority: number;
      readonly is_active: boolean;
      readonly table: string;
      readonly logical_operator: string;
      readonly action_type: string;
      readonly type: string;
      readonly conditions: App.Data.BookkeepingRuleConditionData[];
      readonly actions: App.Data.BookkeepingRuleActionData[];
    };
    export type BookmarkData = {
      readonly id: number;
      readonly name: string;
      readonly route_name: string;
      readonly route_params: Array<any>;
      readonly is_pinned: boolean;
      readonly pos: number;
      readonly model: string;
      readonly sidebar_title: string;
      readonly title: string;
    };
    export type BookmarkFolderData = {
      readonly id: number;
      readonly name: string;
      readonly pos: number;
      readonly bookmarks: App.Data.BookmarkData[];
    };
    export type CompanyData = {
      readonly id: number | null;
      readonly name: string;
      readonly first_name: string | null;
      readonly full_name: string;
      readonly reverse_full_name: string;
      readonly initials: string;
      readonly title_id: number | null;
      readonly salutation_id: number | null;
      readonly creditor_number: string | null;
      readonly is_favorite: boolean | null;
      readonly is_org: boolean | null;
      readonly debtor_number: string | null;
      readonly primary_mail: string | null;
      readonly vat_id: string | null;
      readonly short_name: string | null;
      readonly register_court: string | null;
      readonly register_number: string | null;
      readonly department: string | null;
      readonly position: string | null;
      readonly tax_number: string | null;
      readonly formated_debtor_number: string | null;
      readonly formated_creditor_number: string | null;
      readonly payment_deadline_id: string | null;
      readonly tax_id: string | null;
      readonly iban: string | null;
      readonly paypal_email: string | null;
      readonly cc_name: string | null;
      readonly outturn_account_id: number | null;
      readonly website: string | null;
      readonly is_primary: boolean | null;
      readonly is_debtor: boolean | null;
      readonly is_creditor: boolean | null;
      readonly primary_phone: string | null;
      readonly cost_center_id: number | null;
      readonly cost_center: App.Data.CostCenterData | null;
      avatar_url: string | null;
      readonly outturn_account: App.Data.BookkeepingAccountData;
      readonly contacts: App.Data.ContactData[];
      readonly title: App.Data.TitleData;
      readonly salutation: App.Data.SalutationData;
      readonly payment_deadline: App.Data.PaymentDeadlineData;
      readonly tax: App.Data.TaxData;
      readonly mails: App.Data.ContactMailData[];
      readonly phones: App.Data.ContactPhoneData[];
      readonly sales: App.Data.SalesData;
      readonly addresses: App.Data.ContactAddressData[];
    };
    export type ContactAddressData = {
      readonly id: number | null;
      readonly contact_id: number;
      readonly address: string;
      readonly zip: string;
      readonly city: string;
      readonly country_id: number;
      readonly full_address: Array<any>;
      address_category_id: number;
      readonly category: App.Data.AddressCategoryData;
      readonly country: App.Data.CountryData;
    };
    export type ContactData = {
      readonly id: number | null;
      readonly name: string;
      readonly first_name: string | null;
      readonly company_name: string | null;
      readonly company_id: number | null;
      readonly full_name: string;
      readonly reverse_full_name: string;
      readonly initials: string;
      readonly title_id: number | null;
      readonly salutation_id: number | null;
      readonly creditor_number: string | null;
      readonly note: string | null;
      readonly is_favorite: boolean | null;
      readonly is_org: boolean | null;
      readonly debtor_number: string | null;
      readonly primary_mail: string | null;
      readonly vat_id: string | null;
      readonly short_name: string | null;
      readonly register_court: string | null;
      readonly register_number: string | null;
      readonly department: string | null;
      readonly position: string | null;
      readonly tax_number: string | null;
      readonly formated_debtor_number: string | null;
      readonly formated_creditor_number: string | null;
      readonly payment_deadline_id: number | null;
      readonly tax_id: number | null;
      readonly iban: string | null;
      readonly paypal_email: string | null;
      readonly cc_name: string | null;
      readonly outturn_account_id: number | null;
      readonly website: string | null;
      readonly is_primary: boolean | null;
      readonly is_debtor: boolean | null;
      readonly is_archived: boolean | null;
      readonly is_creditor: boolean | null;
      readonly has_dunning_block: boolean | null;
      readonly primary_phone: string | null;
      readonly cost_center_id: number | null;
      readonly cost_center: App.Data.CostCenterData | null;
      avatar_url: string | null;
      readonly invoice_contact_id: number | null;
      readonly outturn_account: App.Data.BookkeepingAccountData;
      readonly company: App.Data.CompanyData | null;
      readonly dob: string | null;
      readonly contacts: App.Data.ContactData[];
      readonly invoice_contact: App.Data.ContactData | null;
      readonly title: App.Data.TitleData;
      readonly salutation: App.Data.SalutationData;
      readonly payment_deadline: App.Data.PaymentDeadlineData;
      readonly tax: App.Data.TaxData;
      readonly mails: App.Data.ContactMailData[];
      readonly phones: App.Data.ContactPhoneData[];
      readonly sales: App.Data.SalesData;
      readonly addresses: App.Data.ContactAddressData[];
      readonly primary_contact_id: number | null;
      readonly zugferd_profile: App.Enums.ZugferdProfileEnum | null;
      readonly zugferd_route_id: string | null;
    };
    export type ContactMailData = {
      readonly id: number | null;
      readonly contact_id: number;
      readonly email: string;
      readonly pos: number;
      readonly email_category_id: number;
      readonly category: App.Data.EmailCategoryData;
    };
    export type ContactPhoneData = {
      readonly id: number | null;
      readonly contact_id: number;
      readonly phone: string;
      readonly pos: number;
      readonly phone_category_id: number;
      readonly category: App.Data.PhoneCategoryData;
    };
    export type CostCenterData = {
      readonly id: number | null;
      readonly name: string;
      readonly bookkeeping_account_id: number | null;
      readonly account: App.Data.BookkeepingAccountData | null;
    };
    export type CountryData = {
      readonly id: number;
      readonly name: string;
      readonly iso_code: string;
      readonly vehicle_code: string;
      readonly country_code: string;
    };
    export type CurrencyData = {
      readonly id: number | null;
      readonly name: string;
      readonly code: string;
    };
    export type DocumentData = {
      readonly id: number | null;
      readonly document_type_id: number | null;
      readonly sender_contact_id: number | null;
      readonly receiver_contact_id: number | null;
      readonly project_id: number | null;
      readonly filename: string;
      readonly mime_type: string;
      readonly file_size: number;
      readonly pages: number;
      readonly issued_on: string | null;
      readonly sent_on: string | null;
      readonly received_on: string | null;
      readonly deleted_at: string | null;
      readonly is_inbound: boolean | null;
      readonly is_hidden: boolean | null;
      readonly source_file: string | null;
      readonly folder: string;
      readonly title: string;
      readonly label: string | null;
      readonly summary: string | null;
      readonly fulltext: string | null;
      readonly reference: string | null;
      readonly is_pinned: boolean;
      readonly is_confirmed: boolean;
      readonly sender_contact: App.Data.ContactData | null;
      readonly receiver_contact: App.Data.ContactData | null;
      readonly type: App.Data.DocumentTypeData | null;
      readonly project: App.Data.ProjectData | null;
    };
    export type DocumentTypeData = {
      readonly id: number | null;
      readonly parent_id: number | null;
      readonly name: string;
      readonly color: string | null;
      readonly icon: string | null;
    };
    export type DropboxData = {
      readonly id: number | null;
      readonly email_address: string;
      readonly token: string;
      readonly name: string;
      readonly is_shared: boolean;
      readonly is_auto_processing: boolean;
      readonly is_private_by_default: boolean;
      readonly user_id: number | null;
      readonly mails_count: number | null;
      readonly user: App.Data.UserData | null;
    };
    export type DropboxInboxAttachmentData = {
      readonly filename: string;
      readonly contentType: string;
      readonly contentDisposition: string;
      readonly contentId: string | null;
      readonly content: Array<any> | string;
      readonly size: number;
    };
    export type DropboxInboxData = {
      readonly id: number;
      readonly dropbox_id: number;
      readonly from: string;
      readonly to: string[];
      readonly dropbox: App.Data.DropboxData;
      readonly is_private: boolean;
      readonly subject: string;
      readonly plain_body: string;
      readonly attachments: App.Data.DropboxInboxAttachmentData[];
      readonly payload: Array<any>;
      readonly date: string | null;
    };
    export type DropboxInboxIndexData = {
      readonly id: number;
      readonly from: string;
      readonly to: string[];
      readonly subject: string;
      readonly plain_body: string;
      readonly date: string | null;
    };
    export type DropboxMailAttachmentData = {
      readonly id: string;
      readonly dropbox_mail_id: string;
      readonly filename: string;
      readonly mime_type: string | null;
      readonly size: number;
    };
    export type DropboxMailData = {
      readonly id: number;
      readonly dropbox_id: number;
      readonly from: string;
      readonly to: string[];
      readonly is_private: boolean;
      readonly subject: string;
      readonly body: string;
      readonly attachments: App.Data.DropboxMailAttachmentData[];
      readonly attachments_count: number | null;
      readonly seen_at: string | null;
      readonly date: string | null;
    };
    export type EmailAccountData = {
      readonly id: number | null;
      readonly is_default: boolean;
      readonly name: string;
      readonly email: string;
      readonly smtp_username: string | null;
      readonly signature: string;
    };
    export type EmailCategoryData = {
      readonly id: number | null;
      readonly name: string;
      readonly type: number | null;
    };
    export type InboxData = {
      readonly id: number | null;
      readonly name: string;
      readonly is_default: boolean;
      readonly email_address: string;
    };
    export type InboxEntryData = {
      readonly id: number;
      readonly from: string;
      readonly to: string;
      readonly subject: string;
      readonly body: string;
      readonly sent_at: string | null;
    };
    export type InvoiceData = {
      readonly id: number | null;
      readonly contact_id: number;
      readonly project_id: number;
      readonly invoice_contact_id: number;
      readonly type_id: number;
      readonly invoice_number: number | null;
      readonly payment_deadline_id: number;
      readonly document_id: number | null;
      readonly is_external: boolean;
      readonly issued_on: string;
      readonly due_on: string | null;
      readonly service_period_begin: string | null;
      readonly service_period_end: string | null;
      readonly dunning_block: boolean;
      readonly is_draft: boolean;
      readonly is_loss_of_receivables: boolean;
      readonly service_provision: string | null;
      readonly vat_id: string | null;
      readonly address: string | null;
      readonly filename: string | null;
      readonly document_number: string | null;
      readonly booking: App.Data.BookkeepingBookingData | null;
      readonly invoice_address: Array<any>;
      readonly formated_invoice_number: string;
      readonly amount_net: number;
      readonly amount_tax: number;
      readonly amount_gross: number;
      readonly payable_sum_amount: number | null;
      readonly amount_open: number | null;
      readonly is_recurring: boolean;
      readonly recurring_interval_units: number | null;
      readonly additional_text: string | null;
      readonly recurring_interval: App.Enums.InvoiceRecurringEnum | null;
      readonly payable: App.Data.PaymentData;
      readonly parent_id: number | null;
      readonly tax_id: number | null;
      readonly parent_invoice: App.Data.ParentInvoiceData | null;
      readonly sent_at: string | null;
      readonly recurring_begin_on: string | null;
      readonly recurring_end_on: string | null;
      readonly type: App.Data.InvoiceTypeData;
      readonly contact: App.Data.ContactData;
      readonly invoice_contact: App.Data.ContactData;
      readonly project: App.Data.ProjectData;
      readonly payment_deadline: App.Data.PaymentDeadlineData;
      readonly lines: App.Data.InvoiceLineData[];
      readonly tax: App.Data.TaxData;
      readonly offer_id: number | null;
      readonly offer: App.Data.OfferData | null;
      readonly dunning_days: number;
      readonly dunning_level: number;
      readonly notables: App.Data.NoteableData[];
      readonly zugferd_profile: App.Enums.ZugferdProfileEnum | null;
      readonly zugferd_route_id: string | null;
      readonly is_zugferd: boolean;
      readonly is_canceled: boolean | null;
    };
    export type InvoiceLineData = {
      readonly id: number | null;
      readonly invoice_id: number;
      readonly type_id: number;
      readonly pos: number;
      readonly tax_id: number;
      readonly quantity: number | null;
      readonly unit: string | null;
      readonly text: string;
      readonly price: number | null;
      readonly amount: number | null;
      readonly tax: number | null;
      readonly tax_rate_id: number;
      readonly rate: App.Data.TaxRateData | null;
      readonly service_period_begin: string | null;
      readonly service_period_end: string | null;
      readonly linked_invoice: App.Data.InvoiceData | null;
    };
    export type InvoiceTypeData = {
      readonly id: number | null;
      readonly print_name: string;
      readonly display_name: string;
      readonly abbreviation: string;
      readonly key: string;
    };
    export type LetterheadData = {
      readonly id: number | null;
      readonly title: string;
      readonly css: string | null;
      readonly is_multi: boolean;
      readonly is_default: boolean;
    };
    export type LoginData = {
      readonly email: string;
      readonly password: string;
      readonly remember: boolean | null;
    };
    export type NoteableData = {
      readonly id: number;
      readonly notable_id: number;
      readonly note: string;
      readonly creator: App.Data.UserData | null;
      readonly created_at: string;
      readonly updated_at: string;
    };
    export type OfferData = {
      readonly id: number | null;
      readonly contact_id: number;
      readonly project_id: number;
      readonly offer_number: number | null;
      readonly issued_on: string;
      readonly valid_until: string | null;
      readonly is_draft: boolean;
      readonly filename: string | null;
      readonly formated_offer_number: string;
      readonly amount_net: number;
      readonly amount_tax: number;
      readonly amount_gross: number;
      readonly additional_text: string | null;
      readonly parent_id: number | null;
      readonly tax_id: number | null;
      readonly address: string | null;
      readonly sent_at: string | null;
      readonly recurring_end_on: string | null;
      readonly contact: App.Data.ContactData | null;
      readonly project: App.Data.ProjectData | null;
      readonly sections: App.Data.OfferOfferSectionData[];
      readonly lines: App.Data.OfferLineData[];
      readonly attachments: App.Data.AttachmentData[];
      readonly tax: App.Data.TaxData | null;
      readonly is_template: boolean | null;
      readonly template_name: string | null;
      readonly status: App.Enums.OfferStatusEnum;
      readonly notables: App.Data.NoteableData[];
    };
    export type OfferLineData = {
      readonly id: number | null;
      readonly offer_id: number;
      readonly type_id: number;
      readonly pos: number;
      readonly tax_id: number;
      readonly quantity: number | null;
      readonly unit: string | null;
      readonly text: string;
      readonly price: number | null;
      readonly amount: number | null;
      readonly tax: number | null;
      readonly tax_rate_id: number;
      readonly rate: App.Data.TaxRateData | null;
    };
    export type OfferOfferSectionData = {
      readonly id: number | null;
      readonly offer_id: number;
      readonly section_id: number;
      readonly pos: number;
      readonly title: string | null;
      readonly content: string | null;
      readonly pagebreak: App.Enums.PagebreakEnum | null;
    };
    export type OfferSectionData = {
      readonly id: number | null;
      readonly name: string;
      readonly default_content: string | null;
      readonly pagebreak: App.Enums.PagebreakEnum | null;
    };
    export type OfficeTemplateData = {
      readonly id: number | null;
      readonly name: string;
      readonly is_default: boolean;
    };
    export type ParentInvoiceData = {
      readonly id: number | null;
      readonly invoice_number: number;
      readonly formated_invoice_number: string;
      readonly issued_on: string | null;
      readonly sent_at: string | null;
    };
    export type PaymentData = {
      readonly id: number | null;
      readonly payable_type: string;
      readonly payable_id: number;
      readonly days: number | null;
      readonly amount: number | null;
      readonly is_currency_difference: boolean | null;
      readonly transaction_id: number;
      readonly transaction: App.Data.TransactionData;
      readonly issued_on: string;
    };
    export type PaymentDeadlineData = {
      readonly id: number | null;
      readonly name: string;
      readonly days: number | null;
      readonly is_immediately: boolean | null;
      readonly is_default: boolean | null;
      readonly invoice_text: string | null;
    };
    export type PhoneCategoryData = {
      readonly id: number | null;
      readonly name: string;
      readonly type: number | null;
    };
    export type PrintLayoutData = {
      readonly id: number | null;
      readonly name: string;
      readonly title: string;
      readonly css: string | null;
      readonly letterhead_id: number;
      readonly letterhead: App.Data.LetterheadData;
    };
    export type ProjectCategoryData = {
      readonly id: number | null;
      readonly name: string;
      readonly color: string | null;
      readonly icon: string | null;
    };
    export type ProjectData = {
      readonly id: number | null;
      readonly name: string;
      readonly website: string | null;
      readonly owner_contact_id: number | null;
      readonly lead_user_id: number | null;
      readonly manager_contact_id: number | null;
      readonly project_category_id: number;
      readonly is_archived: boolean;
      readonly hourly: number;
      readonly budget_hours: number | null;
      readonly budget_costs: number | null;
      readonly budget_period: string | null;
      readonly avatar_url: string | null;
      readonly begin_on: string | null;
      readonly end_on: string | null;
      readonly owner: App.Data.ContactData | null;
      readonly user: App.Data.UserData | null;
      readonly manager: App.Data.ContactData | null;
      readonly category: App.Data.ProjectCategoryData | null;
    };
    export type ReceiptData = {
      readonly id: number | null;
      readonly reference: string;
      readonly issued_on: string;
      readonly org_filename: string;
      readonly file_size: number;
      readonly file_created_at: string;
      readonly open_amount: number;
      readonly payable_min_issued_on: string | null;
      readonly contact_id: number | null;
      readonly cost_center_id: number | null;
      readonly bookkeeping_account_id: number | null;
      readonly org_currency: string | null;
      readonly org_amount: number | null;
      readonly amount: number;
      readonly exchange_rate: number | null;
      readonly document_number: string | null;
      readonly duplicate_of: number | null;
      readonly is_foreign_currency: boolean | null;
      readonly is_confirmed: boolean | null;
      readonly is_locked: boolean;
      readonly bookings_count: number | null;
      readonly iban: string | null;
      readonly number_range_document_number_id: number | null;
      readonly account: App.Data.BookkeepingAccountData | null;
      readonly contact: App.Data.ContactData | null;
      readonly cost_center: App.Data.CostCenterData | null;
      readonly number_range_document_number: unknown | null;
      readonly checksum: string;
      readonly text: string | null;
      readonly data: Array<any> | null;
      readonly payable_sum: number | null;
      readonly payable: App.Data.PaymentData[];
      readonly bookings: App.Data.BookkeepingBookingData[];
      readonly created_at: string;
      readonly updated_at: string;
    };
    export type RegionData = {
      readonly id: number;
      readonly country_id: number;
      readonly name: string;
      readonly short_name: string;
      readonly place_short_name: string;
    };
    export type SalesData = {
      readonly currentYear: number;
      readonly allTime: number;
    };
    export type SalutationData = {
      readonly id: number | null;
      readonly name: string;
      readonly is_hidden: boolean;
      readonly gender: string;
    };
    export type SendEmailData = {
      readonly email: string;
      readonly name: string;
      readonly city: string;
      readonly body: string;
      readonly subject: string;
      readonly email_account_id: number;
    };
    export type SettingData = {
      readonly group: string;
      readonly key: string;
      readonly value: string | null;
    };
    export type SimpleContactData = {
      readonly id: number;
      readonly reverse_full_name: string;
      readonly initials: string;
      readonly primary_mail: string | null;
    };
    export type TaxData = {
      readonly id: number | null;
      readonly name: string;
      readonly invoice_text: string;
      readonly needs_vat_id: boolean;
      readonly is_default: boolean;
      readonly value: number;
      readonly default_rate_id: number;
      readonly rates: App.Data.TaxRateData[];
    };
    export type TaxRateData = {
      readonly id: number | null;
      readonly tax_id: number;
      readonly rate: number;
      readonly name: string;
    };
    export type TenantData = {
      readonly first_name: string;
      readonly last_name: string;
      readonly organisation: string;
      readonly email: string;
      readonly website: string;
      readonly subdomain: string;
      readonly prefix: string;
      readonly formated_prefix: string;
    };
    export type TextModuleData = {
      readonly id: number | null;
      readonly title: string | null;
      readonly content: string | null;
    };
    export type TimeCategoryData = {
      readonly id: number | null;
      readonly name: string;
      readonly short_name: string;
      readonly pos: number;
      readonly is_default: boolean;
      readonly hourly: number;
    };
    export type TimeData = {
      readonly id: number | null;
      readonly project_id: number;
      readonly time_category_id: number;
      readonly subproject_id: number | null;
      readonly task_id: number | null;
      readonly invoice_id: number | null;
      readonly user_id: number;
      readonly note: string | null;
      readonly begin_at: string;
      readonly end_at: string | null;
      readonly date: string;
      readonly is_locked: boolean;
      readonly is_billable: boolean;
      readonly is_timer: boolean;
      readonly minutes: number | null;
      readonly mins: number | null;
      readonly ping_at: string | null;
      readonly created_at: string | null;
      readonly updated_at: string | null;
      readonly deleted_at: string | null;
      readonly project: App.Data.ProjectData;
      readonly subproject: App.Data.ProjectData;
      readonly category: App.Data.TimeCategoryData;
      readonly user: App.Data.UserData;
    };
    export type TimelineEntryData = {
      readonly type: string;
      readonly date: string | null;
      readonly note: App.Data.NoteableData | null;
      readonly mail: App.Data.DropboxMailData | null;
    };
    export type TitleData = {
      readonly id: number | null;
      readonly name: string;
      readonly correspondence_salutation_male: string;
      readonly correspondence_salutation_female: string;
      readonly correspondence_salutation_other: string;
    };
    export type TransactionData = {
      readonly id: number | null;
      readonly mm_ref: string;
      readonly contact_id: number;
      readonly bank_account_id: number;
      readonly valued_on: string;
      readonly booked_on: string | null;
      readonly comment: string | null;
      readonly currency: string;
      readonly booking_key: string | null;
      readonly bank_code: string | null;
      readonly account_number: string | null;
      readonly name: string;
      readonly purpose: string | null;
      readonly amount: number;
      readonly remaining_amount: number;
      readonly is_private: boolean;
      readonly created_at: string | null;
      readonly updated_at: string | null;
      readonly prefix: string;
      readonly booking_text: string | null;
      readonly type: string | null;
      readonly return_reason: string | null;
      readonly transaction_code: string | null;
      readonly end_to_end_reference: string | null;
      readonly mandate_reference: string | null;
      readonly batch_reference: string | null;
      readonly primanota_number: string | null;
      readonly is_transit: boolean;
      readonly booking_id: number | null;
      readonly org_category: string | null;
      readonly amount_in_foreign_currency: number;
      readonly number_range_document_numbers_id: number | null;
      readonly document_number: string | null;
      readonly foreign_currency: string | null;
      readonly counter_account_id: number;
      readonly is_locked: boolean;
      readonly bookkeeping_text: string;
      readonly contact: App.Data.ContactData;
      readonly account: App.Data.BookkeepingAccountData;
      readonly booking: App.Data.BookkeepingBookingData | null;
    };
    export type UserData = {
      readonly id: number | null;
      readonly first_name: string;
      readonly last_name: string;
      readonly avatar_url: string | null;
      readonly is_admin: boolean;
      readonly is_locked: boolean;
      readonly email: string;
      readonly full_name: string;
      readonly reverse_full_name: string;
      readonly initials: string;
      readonly user_agent: string | null;
      readonly pending_email: string | null;
      readonly is_impersonating: boolean | null;
      readonly impersonator: string | null;
      readonly email_account_id: number | null;
      readonly contact_id: number | null;
      readonly email_account: App.Data.EmailAccountData | null;
      readonly contact: App.Data.ContactData | null;
      readonly last_login_at: string | null;
      readonly email_verified_at: string | null;
    };
    export type ZugferdSettingData = {
      readonly is_enabled: boolean | null;
      readonly seller_contact_id: number | null;
      readonly seller_contact_person_id: number | null;
      readonly seller_contact_address_id: number | null;
      readonly document_note: string | null;
      readonly global_id_type: string | null;
      readonly global_id: string | null;
    };
  }
  namespace Enums {
    export type InboxEntryStatus = "pending" | "accepted" | "rejected";
    export type InvoiceRecurringEnum = "days" | "weeks" | "months" | "years";
    export type OfferStatusEnum =
      | "pending"
      | "accepted"
      | "rejected"
      | "postponed"
      | "extended"
      | "canceled";
    export type PagebreakEnum = "after" | "before" | "both" | "none";
    export type ZugferdProfileEnum = "zugferd" | "xrechnung3";
  }
}
