/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Body: typeof import('./../node_modules/.pnpm/@maizzle+framework@6.0.0-rc.18_@vue+compiler-sfc@3.5.33_esbuild@0.27.7_lightningcss@1.3_e4cfae19429afb763e28d0427b5e9473/node_modules/@maizzle/framework/dist/components/Body.vue')['default']
    Button: typeof import('./../node_modules/.pnpm/@maizzle+framework@6.0.0-rc.18_@vue+compiler-sfc@3.5.33_esbuild@0.27.7_lightningcss@1.3_e4cfae19429afb763e28d0427b5e9473/node_modules/@maizzle/framework/dist/components/Button.vue')['default']
    CodeBlock: typeof import('./../node_modules/.pnpm/@maizzle+framework@6.0.0-rc.18_@vue+compiler-sfc@3.5.33_esbuild@0.27.7_lightningcss@1.3_e4cfae19429afb763e28d0427b5e9473/node_modules/@maizzle/framework/dist/components/CodeBlock.vue')['default']
    CodeInline: typeof import('./../node_modules/.pnpm/@maizzle+framework@6.0.0-rc.18_@vue+compiler-sfc@3.5.33_esbuild@0.27.7_lightningcss@1.3_e4cfae19429afb763e28d0427b5e9473/node_modules/@maizzle/framework/dist/components/CodeInline.vue')['default']
    Column: typeof import('./../node_modules/.pnpm/@maizzle+framework@6.0.0-rc.18_@vue+compiler-sfc@3.5.33_esbuild@0.27.7_lightningcss@1.3_e4cfae19429afb763e28d0427b5e9473/node_modules/@maizzle/framework/dist/components/Column.vue')['default']
    Container: typeof import('./../node_modules/.pnpm/@maizzle+framework@6.0.0-rc.18_@vue+compiler-sfc@3.5.33_esbuild@0.27.7_lightningcss@1.3_e4cfae19429afb763e28d0427b5e9473/node_modules/@maizzle/framework/dist/components/Container.vue')['default']
    Font: typeof import('./../node_modules/.pnpm/@maizzle+framework@6.0.0-rc.18_@vue+compiler-sfc@3.5.33_esbuild@0.27.7_lightningcss@1.3_e4cfae19429afb763e28d0427b5e9473/node_modules/@maizzle/framework/dist/components/Font.vue')['default']
    Head: typeof import('./../node_modules/.pnpm/@maizzle+framework@6.0.0-rc.18_@vue+compiler-sfc@3.5.33_esbuild@0.27.7_lightningcss@1.3_e4cfae19429afb763e28d0427b5e9473/node_modules/@maizzle/framework/dist/components/Head.vue')['default']
    Heading: typeof import('./../node_modules/.pnpm/@maizzle+framework@6.0.0-rc.18_@vue+compiler-sfc@3.5.33_esbuild@0.27.7_lightningcss@1.3_e4cfae19429afb763e28d0427b5e9473/node_modules/@maizzle/framework/dist/components/Heading.vue')['default']
    Hr: typeof import('./../node_modules/.pnpm/@maizzle+framework@6.0.0-rc.18_@vue+compiler-sfc@3.5.33_esbuild@0.27.7_lightningcss@1.3_e4cfae19429afb763e28d0427b5e9473/node_modules/@maizzle/framework/dist/components/Hr.vue')['default']
    Html: typeof import('./../node_modules/.pnpm/@maizzle+framework@6.0.0-rc.18_@vue+compiler-sfc@3.5.33_esbuild@0.27.7_lightningcss@1.3_e4cfae19429afb763e28d0427b5e9473/node_modules/@maizzle/framework/dist/components/Html.vue')['default']
    Img: typeof import('./../node_modules/.pnpm/@maizzle+framework@6.0.0-rc.18_@vue+compiler-sfc@3.5.33_esbuild@0.27.7_lightningcss@1.3_e4cfae19429afb763e28d0427b5e9473/node_modules/@maizzle/framework/dist/components/Img.vue')['default']
    Layout: typeof import('./../node_modules/.pnpm/@maizzle+framework@6.0.0-rc.18_@vue+compiler-sfc@3.5.33_esbuild@0.27.7_lightningcss@1.3_e4cfae19429afb763e28d0427b5e9473/node_modules/@maizzle/framework/dist/components/Layout.vue')['default']
    Link: typeof import('./../node_modules/.pnpm/@maizzle+framework@6.0.0-rc.18_@vue+compiler-sfc@3.5.33_esbuild@0.27.7_lightningcss@1.3_e4cfae19429afb763e28d0427b5e9473/node_modules/@maizzle/framework/dist/components/Link.vue')['default']
    Markdown: typeof import('./../node_modules/.pnpm/@maizzle+framework@6.0.0-rc.18_@vue+compiler-sfc@3.5.33_esbuild@0.27.7_lightningcss@1.3_e4cfae19429afb763e28d0427b5e9473/node_modules/@maizzle/framework/dist/components/Markdown.vue')['default']
    MarkdownLayout: typeof import('./../node_modules/.pnpm/@maizzle+framework@6.0.0-rc.18_@vue+compiler-sfc@3.5.33_esbuild@0.27.7_lightningcss@1.3_e4cfae19429afb763e28d0427b5e9473/node_modules/@maizzle/framework/dist/components/MarkdownLayout.vue')['default']
    NotOutlook: typeof import('./../node_modules/.pnpm/@maizzle+framework@6.0.0-rc.18_@vue+compiler-sfc@3.5.33_esbuild@0.27.7_lightningcss@1.3_e4cfae19429afb763e28d0427b5e9473/node_modules/@maizzle/framework/dist/components/NotOutlook.vue')['default']
    NoWidows: typeof import('./../node_modules/.pnpm/@maizzle+framework@6.0.0-rc.18_@vue+compiler-sfc@3.5.33_esbuild@0.27.7_lightningcss@1.3_e4cfae19429afb763e28d0427b5e9473/node_modules/@maizzle/framework/dist/components/NoWidows.vue')['default']
    Outlook: typeof import('./../node_modules/.pnpm/@maizzle+framework@6.0.0-rc.18_@vue+compiler-sfc@3.5.33_esbuild@0.27.7_lightningcss@1.3_e4cfae19429afb763e28d0427b5e9473/node_modules/@maizzle/framework/dist/components/Outlook.vue')['default']
    Overlap: typeof import('./../node_modules/.pnpm/@maizzle+framework@6.0.0-rc.18_@vue+compiler-sfc@3.5.33_esbuild@0.27.7_lightningcss@1.3_e4cfae19429afb763e28d0427b5e9473/node_modules/@maizzle/framework/dist/components/Overlap.vue')['default']
    Preheader: typeof import('./../node_modules/.pnpm/@maizzle+framework@6.0.0-rc.18_@vue+compiler-sfc@3.5.33_esbuild@0.27.7_lightningcss@1.3_e4cfae19429afb763e28d0427b5e9473/node_modules/@maizzle/framework/dist/components/Preheader.vue')['default']
    Raw: typeof import('./../node_modules/.pnpm/@maizzle+framework@6.0.0-rc.18_@vue+compiler-sfc@3.5.33_esbuild@0.27.7_lightningcss@1.3_e4cfae19429afb763e28d0427b5e9473/node_modules/@maizzle/framework/dist/components/Raw.vue')['default']
    Row: typeof import('./../node_modules/.pnpm/@maizzle+framework@6.0.0-rc.18_@vue+compiler-sfc@3.5.33_esbuild@0.27.7_lightningcss@1.3_e4cfae19429afb763e28d0427b5e9473/node_modules/@maizzle/framework/dist/components/Row.vue')['default']
    Section: typeof import('./../node_modules/.pnpm/@maizzle+framework@6.0.0-rc.18_@vue+compiler-sfc@3.5.33_esbuild@0.27.7_lightningcss@1.3_e4cfae19429afb763e28d0427b5e9473/node_modules/@maizzle/framework/dist/components/Section.vue')['default']
    Spacer: typeof import('./../node_modules/.pnpm/@maizzle+framework@6.0.0-rc.18_@vue+compiler-sfc@3.5.33_esbuild@0.27.7_lightningcss@1.3_e4cfae19429afb763e28d0427b5e9473/node_modules/@maizzle/framework/dist/components/Spacer.vue')['default']
    Tailwind: typeof import('./../node_modules/.pnpm/@maizzle+framework@6.0.0-rc.18_@vue+compiler-sfc@3.5.33_esbuild@0.27.7_lightningcss@1.3_e4cfae19429afb763e28d0427b5e9473/node_modules/@maizzle/framework/dist/components/Tailwind.vue')['default']
    Text: typeof import('./../node_modules/.pnpm/@maizzle+framework@6.0.0-rc.18_@vue+compiler-sfc@3.5.33_esbuild@0.27.7_lightningcss@1.3_e4cfae19429afb763e28d0427b5e9473/node_modules/@maizzle/framework/dist/components/Text.vue')['default']
    Vml: typeof import('./../node_modules/.pnpm/@maizzle+framework@6.0.0-rc.18_@vue+compiler-sfc@3.5.33_esbuild@0.27.7_lightningcss@1.3_e4cfae19429afb763e28d0427b5e9473/node_modules/@maizzle/framework/dist/components/Vml.vue')['default']
    WithUrl: typeof import('./../node_modules/.pnpm/@maizzle+framework@6.0.0-rc.18_@vue+compiler-sfc@3.5.33_esbuild@0.27.7_lightningcss@1.3_e4cfae19429afb763e28d0427b5e9473/node_modules/@maizzle/framework/dist/components/WithUrl.vue')['default']
  }
}
